version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=caiopcabral
      - POSTGRES_PASSWORD=0102
      - POSTGRES_DB=api      
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/docker-db-initial.sql:/docker-entrypoint-initdb.d/docker-db-initial.sql   

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "caiiocabral42@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "0102"
    ports:
      - "54321:80"
    depends_on:
      - postgres